### ISSUE TITLE
isValid is exported as validate

### ISSUE THREAD

**Issue by WaldoJeffers** [aymericbouzy/french-ssn#1]
Hello,

This seems to be a very nice library. I was about to create one with the same purpose before stumbling upon `french-ssn`. The README documents a `isValid` function, but the library exports a [`validate` function](https://github.com/aymericbouzy/french-ssn/blob/master/src/index.js#L18). This will be easy to fix but it can confuse newcomers ^^

**Comment by aymericbouzy** [comment]
Sorry for not answering earlier, I was on holiday. This is a very good point, want to make a PR? Also, don't hesitate creating issues for things that might be missing in this package, i'll be glad to have a look into it.

**Comment by WaldoJeffers** [comment]
@aymericbouzy Sure! Which name do you want to keep? `isValid` or `validate`?

**Comment by aymericbouzy** [comment]
I think it's better not to break anything : only editing the documentation seems a better choice. Therefore I would keep `validate`.

**Comment by WaldoJeffers** [comment]
Sure, fix is in https://github.com/aymericbouzy/french-ssn/pull/2
