### ISSUE TITLE
Types declaration

### ISSUE THREAD

**Issue by raydaim** [aymericbouzy/french-ssn#23]
Hello, Thank you for the library! it is so useful  I am using it in my type script project, but the ts compiler is complaining about the missing types can you add them please 
![image](https://user-images.githubusercontent.com/7352384/94416771-880d9d00-017f-11eb-9468-5c80e6a4a5b1.png)

**Comment by aymericbouzy** [comment]
@raydaim I'm very glad it's useful to you 😊 are you still interested in that feature?

**Comment by aymericbouzy** [comment]
Release candidate is available, refactored in TS, you can install with:

```sh
yarn add french-ssn@beta
```

and make feedbacks if you run into any issue 🙏
