### ISSUE TITLE
bug: wrong country response when parsing SSN

### ISSUE THREAD

**Issue by pdavim** [aymericbouzy/french-ssn#41]
SSN: 195029851007603
Expected 
country should be PAPPUA/NEWGUINÉ code 510

Actual result
{ "birth": { "month": { "name": "février", "index": 2 }, "year": 1995, "country": { "unknown": true }, "county": { "unknown": true, "insee": "985", "error": "appears to be incorrect" }, "city": { "insee": "98510" }, "approximateDate": "1995-02-15T00:00:00.000Z" }, "gender": { "name": "male", "title": "M" }, "provisional": false, "approximateAge": 28 }

**Comment by aymericbouzy** [comment]
First time I see this, I was expecting it to be code [99510](https://www.insee.fr/fr/information/2028273#:~:text=99517%20PALAOS%20(ILES)-,99510,-PAPOUASIE%2DNOUVELLE%2DGUINEE)

Are you certain that the person with that SSN was born in Papua New Guinea?

**Comment by aymericbouzy** [comment]
It seems [98510 points to Koungou in Mayotte](https://simple.wikipedia.org/wiki/Communes_of_Mayotte#:~:text=97600-,98510,-Mamoudzou) no?
